src/Entity/Command.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OneToMany;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommandRepository")
 * @UniqueEntity("reference")
 */
class Command
{
    const STATE = [
        "0" => "En attente de fichier",
        "1" => "En attente de B.A.T.",
        "2" => "En cours de production",
        "3" => "En cours de livraison",
        "4" => "Livrée",
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Regex(pattern="/[0-9]{6}[\.][0-9]{4}$/", htmlPattern=false, message="La référence doit être de la forme 000000.0000")
     * @ORM\Column(type="string", length=255)
     */
    public $reference;

    /**
     * @ORM\Column(type="integer", options={"default":0})
     */
    private $state = 0;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    public $updated_at;

    /**
     * One command has many items. This is the inverse side.
     * @OneToMany(targetEntity="Item", mappedBy="command", cascade={"persist"})
     */
    private $items;

    /**
     * Command constructor.
     * @throws \Exception
     */
    public function __construct()
    {
        $this->items = new ArrayCollection();
        $this->created_at = new \DateTime();
        $this->updated_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getState(): ?int
    {
        return $this->state;
    }

    public function setState(int $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getStateType(): string
    {
        return self::STATE[$this->getState()];
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Item[]
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(Item $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items->add($item);
            $item->addCommand($this);
        }

        return $this;
    }

    public function removeItem(Item $item): self
    {
        if ($this->items->contains($item)) {
            $this->items->removeElement($item);
        }

        return $this;
    }
}

src/Entity/Item.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\ManyToOne;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ItemRepository")
 * @Vich\Uploadable
 */
class Item
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * Many items have one command. This is the owning side.
     * @ManyToOne(targetEntity="Command", inversedBy="items", cascade={"persist"})
     * @JoinColumn(name="command_id", referencedColumnName="id")
     */
    private $command;

    /**
     * Many items have one product. This is the owning side.
     * @ManyToOne(targetEntity="Product", inversedBy="items", cascade={"persist"})
     * @JoinColumn(name="product_id", referencedColumnName="id")
     */
    private $product;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string|null
     */
    private $filename;

    /**
     * @Vich\UploadableField(mapping="item_files", fileNameProperty="filename")
     * @var File|null
     */
    public $file;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $estimatedDelivery;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $realDelivery;

    /**
     * Many items have one address. This is the owning side.
     * @ManyToOne(targetEntity="User", inversedBy="items", cascade={"persist"})
     * @JoinColumn(name="deliver_to_id", referencedColumnName="id")
     */
    private $deliverTo;

    /**
     * @ORM\Column(type="boolean")
     */
    private $delivered;

    /**
     * Item constructor.
     * @throws \Exception
     */
    public function __construct()
    {
        $this->command = new ArrayCollection();
        $this->product = new ArrayCollection();
        $this->updated_at = new \DateTime();
        $this->delivered = false;
    }

    /**
     * @return integer
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return ArrayCollection
     */
    public function getCommand()
    {
        return $this->command;
    }

    public function addCommand(Command $command): self
    {
        $this->command = $command;
        return $this;
    }

    public function setCommand($command): self
    {
        $this->command = $command;
        return $this;
    }

    /**
     * @return ArrayCollection
     */
    public function getProduct()
    {
        return $this->product;
    }

    public function setProduct($product)
    {
        $this->product = $product;
        return $this;
    }

    public function getOrderedQuantity()
    {
        return $this->quantity;
    }

    public function setOrderedQuantity($quantity)
    {
        $this->quantity = $quantity;
        return $this;
    }

    public function addProduct(Product $product)
    {
        if (!$this->product->contains($product)) {
            $this->product->removeElement($product);
        }
        return $this;
    }

    public function removeProduct(Product $product)
    {
        if ($this->product->contains($product)) {
            $this->product->removeElement($product);
        }
        return $this;
    }

    /**
     * @return string|null
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param string|null $filename
     * @return Item
     */
    public function setFilename(?string $filename): Item
    {
        $this->filename = $filename;
        return $this;
    }

    /**
     * @return File|null
     */
    public function getFile(): ?File
    {
        return $this->file;
    }

    /**
     * @param File $file
     * @return Item
     * @throws \Exception
     */
    public function setFile(File $file): Item
    {
        $this->file = $file;
        if ($this->file instanceof UploadedFile) {
            $this->command->updated_at = new \DateTime('now');
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getEstimatedDelivery(): ?\DateTimeInterface
    {
        return $this->estimatedDelivery;
    }

    public function setEstimatedDelivery(?\DateTimeInterface $estimatedDelivery): self
    {
        $this->estimatedDelivery = $estimatedDelivery;

        return $this;
    }

    public function getRealDelivery(): ?\DateTimeInterface
    {
        return $this->realDelivery;
    }

    public function setRealDelivery(?\DateTimeInterface $realDelivery): self
    {
        $this->realDelivery = $realDelivery;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getDeliverTo()
    {
        return $this->deliverTo;
    }

    public function setDeliverTo($deliverTo): self
    {
        $this->deliverTo = $deliverTo;

        return $this;
    }

    public function getDelivered(): ?bool
    {
        return $this->delivered;
    }

    public function setDelivered(bool $delivered): self
    {
        $this->delivered = $delivered;

        return $this;
    }
}

src/Form/CommandType.php
<?php

namespace App\Form;

use App\Entity\Command;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommandType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     * @throws \Exception
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('reference', TextType::class)
            ->add('items', CollectionType::class, [
                'label' => false,
                'entry_type' => ItemType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false
            ])
            ->add('state', ChoiceType::class, [
                'choices' => array_flip(Command::STATE)
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Command::class,
            'translation_domain' => 'forms.command'
        ]);
    }
}

src/Controller/CommandController.php
<?php

namespace App\Controller;

//use App\Entity\Command;
use App\Entity\CommandSearch;
use App\Form\CommandSearchType;
use App\Repository\CommandRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CommandController extends AbstractController
{
    /**
     * @var CommandRepository
     */
    private $repository;
    /**
     * @var EntityManagerInterface
     */
    private $em;

    /**
     * CommandController constructor.
     * @param CommandRepository $repository
     * @param EntityManagerInterface $em
     */
    public function __construct(CommandRepository $repository, EntityManagerInterface $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }

    /**
     * @Route("/commands", name="command.index")
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $search = new CommandSearch();
        $form = $this->createForm(CommandSearchType::class, $search);
        $form->handleRequest($request);

        $commands = $paginator->paginate(
            $this->repository->findAllQuery($search),
            $request->query->getInt('page', 1),
            9
        );

        return $this->render('command/index.html.twig', [
            'commands' => $commands,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/commands/{reference}", name="command.show", requirements={"reference": "[0-9]{6}[\.][0-9]{4}$"})
     * @param string $reference
     * @return Response
     */
    public function show(string $reference): Response
    {
        $command = $this->repository->findOneBy(['reference' => $reference]);
        return $this->render('command/show.html.twig', [
            'command' => $command,
        ]);
    }
}

templates/command/_form.html.twig
{{ form_start(form, {'attr':{'class': 'mb-4'}}) }}
<div class="bg-light pt-3 px-3 pb-1 mt-4 mb-3">
    <div class="form-row">
        <div class="col-md-5">
            {{ form_row(form.searchInput) }}
        </div>
        <div class="form-group col-md-7">
            {{ form_label(form.searchBy) }}
            <div class="form-inline">
                {{ form_widget(form.searchBy) }}
                <button type="submit" class="btn btn-primary ml-2">Rechercher</button>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="col-md-1">Afficher :</div>
        <div class="col-md-11">
            <div class="row">
                {{ form_widget(form.state) }}
            </div>
        </div>
    </div>
</div>
<div class="pt-3 pb-1 mt-2 mb-4">
    <div class="form-row align-items-center">
        <div class="col-auto">
            {{ form_label(form.orderBy) }} :
        </div>
        <div class="col-auto">
            {{ form_widget(form.orderBy, {'attr':{'onchange': 'this.form.submit()'}}) }}
        </div>
        <div class="col-auto">
            {{ form_widget(form.orderDirection) }}
        </div>
    </div>
</div>
{{ form_end(form, {'render_rest' : false}) }}

templates/command/index.html.twig
{% extends 'base.html.twig' %}

{% block title "Voir les commandes" %}

{% block body %}
    <div class="container my-4">
        <h1>Voir les commandes</h1>
        {{ include('command/_form.html.twig') }}
        <div class="row">
            {% for command in commands %}
                <div class="col-md-4 col-sm mb-2 mb-md-3">
                    <div class="card">
                        <div class="card-body d-flex">
                            <div>
                                <h3 class="ref">n° commande: {{ command.reference }}</h3>
                                <h5 class="ref">refs. produit:</h5>
                                <ul>
                                    {% for item in command.items %}
                                        <li>{{ item.product.reference }} : {{ item.orderedQuantity }}</li>
                                    {% endfor %}
                                </ul>
                                <h5 class="ref">commandée le: </h5><span
                                        class="red">{{ command.createdAt.date|date('d/m/Y \\à H\\hi', 'Europe/Paris') }}</span>
                                <h5 class="ref">mise à jour le: </h5><span
                                        class="red">{{ command.updatedAt.date|date('d/m/Y \\à H\\hi', 'Europe/Paris') }}</span>
                                <h5 class="ref">État: </h5><span>{{ command.stateType }}</span>
                            </div>
                            <div class="ml-auto">
                                <a href="{{ path('command.show', {reference: command.reference}) }}">
                                    icone
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="pagination pagination-container text-center w-100 d-flex justify-content-center">
            {{ knp_pagination_render(commands) }}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        jQuery('#orderDirection .form-check input').on('change', function (e) {
            this.form.submit();
        });
    </script>
{% endblock %}

templates/command/show.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
{% endblock %}

{% block title %}Détails pour {{ command.reference }}{% endblock %}

{% block body %}
    <div class="container my-4">
        <a href="{{ path('command.index') }}">Retour aux commandes</a>
        <h1 class="red">Détails pour la commande {{ command.reference }}</h1>
        <div class="order-tracking-line-container">
            <div class="order-tracking-line tracking-state-{{ command.state }}">
                <div class="tracking-step tracking-step-files">
                    <div class="tracking-point"></div>
                    <div class="tracking-text">{{ command.state >= 1 ? 'fichier(s) reçu(s)' : 'en attente de fichier(s)' }}</div>
                </div>
                <div class="tracking-step tracking-step-proof">
                    <div class="tracking-point"></div>
                    <div class="tracking-text">{{ command.state >= 2 ? 'B.A.T. reçu' : command.state == 1 ? 'En attente de B.A.T' : '&nbsp;' }}</div>
                </div>
                <div class="tracking-step tracking-step-prod">
                    <div class="tracking-point"></div>
                    <div class="tracking-text">{{ command.state >= 3 ? 'Production terminée' : command.state == 2 ? 'En cours de production' : '&nbsp;' }}</div>
                </div>
                <div class="tracking-step tracking-step-ship">
                    <div class="tracking-point"></div>
                    <div class="tracking-text">{{ command.state == 4 ? 'Livrée' : command.state == 3 ? 'En cours de livraison' : '&nbsp;' }}</div>
                </div>
            </div>
        </div>
        <div class="order-blocks">
            <div class="order-block order-infos">
                <h2 class="order-block-title">Informations sur la commande :</h2>
                <div class="order-block-content">
                    <p><b>Commande passée le
                            : </b>{{ command.createdAt.date|date('d/m/Y \\à H\\hi', 'Europe/Paris') }}
                    </p>
                    <p><b>Commande mise à jour le
                            : </b>{{ command.updatedAt.date|date('d/m/Y \\à H\\hi', 'Europe/Paris') }}</p>
                    {% if FALSE %}
                        <a href="#" data-toggle="modal" data-target="#filesModal">
                            Voir les fichiers joints (<span class="text-danger font-weight-bold">WIP</span>)
                        </a>
                    {% endif %}
                </div>
            </div>
            <div class="order-block order-products">
                <h2 class="order-block-title">Contenu de la commande :</h2>
                <table id="productsTable" class="table table-striped table-bordered table-sm" cellspacing="0"
                       width="100%">
                    <thead>
                    <tr>
                        <th>Référence produit</th>
                        <th>Quantité commandée</th>
                        <th>Quantité en stock</th>
                        <th>Quantité critique</th>
                        <th>Livrer à</th>
                        <th>Livraison estimée</th>
                        <th>Livré</th>
                        <th>Fichier(s) joint(s)</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in command.items %}
                        <tr>
                            <td>
                                <a href="{{ path('product.show', {'reference': item.product.reference}) }}" target="_blank">{{ item.product.reference }}</a>
                            </td>
                            <td>{{ item.orderedQuantity }}</td>
                            <td>{{ item.product.quantity }}</td>
                            <td>{{ item.product.critical|default('Non défini') }}</td>
                            <td><a href="{{ path('address.show', {'id': item.deliverTo.id}) }}"
                                   target="_blank">{{ item.deliverTo.name }}</a></td>
                            <td>{{ item.estimatedDelivery.date|date('d-m-Y', 'Europe/Paris') }}</td>
                            <td>{{ item.realDelivery ? item.realDelivery.date|date('d-m-Y', 'Europe/Paris') : 'Non' }}</td>
                            <td>
                                {% if item.filename %}
                                    <a href="{{ vich_uploader_asset(item,'file') }}">{{ item.filename }}</a>
                                {% else %}
                                    Aucun fichier joint
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="order-block order-tracking">
                <h2 class="order-block-title">Suivi de la livraison :</h2>
                <div class="order-block-content">
                    <span class="text-danger font-weight-bold">WIP</span>
                </div>
            </div>
            {% if FALSE %}
                <div class="modal fade bd-example-modal-lg" id="filesModal" tabindex="-1" role="dialog"
                     aria-labelledby="myLargeModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-lg modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h3 class="modal-title red">Fichiers joints</h3>
                                <button type="button" class="close-icon" data-dismiss="modal" aria-label="Close">
                                    <img src="">
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="row files-container">
                                    <div class="col-2 text-break single-file">
                                        <div class="file-icon-container px-2">
                                            <img src="#" alt=""
                                                 class="file-icon img-fluid">
                                        </div>
                                        <p class="text-break text-center mt-1 d-inline-block w-100">
                                            WIP
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
{% endblock %}