src/Entity/Address.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OneToMany;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AddressRepository")
 */
class Address
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $department;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address_line_1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address_line_2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address_line_3;

    /**
     * One address has many items. This is the inverse side.
     * @OneToMany(targetEntity="Item", mappedBy="deliverTo", cascade={"persist"})
     */
    private $items;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\User", mappedBy="address")
     */
    private $users;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getDepartment(): ?string
    {
        return $this->department;
    }

    public function setDepartment(string $department): self
    {
        $this->department = $department;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getAddressLine1(): ?string
    {
        return $this->address_line_1;
    }

    public function setAddressLine1(string $address_line_1): self
    {
        $this->address_line_1 = $address_line_1;

        return $this;
    }

    public function getAddressLine2(): ?string
    {
        return $this->address_line_2;
    }

    public function setAddressLine2(string $address_line_2): self
    {
        $this->address_line_2 = $address_line_2;

        return $this;
    }

    public function getAddressLine3(): ?string
    {
        return $this->address_line_3;
    }

    public function setAddressLine3(string $address_line_3): self
    {
        $this->address_line_3 = $address_line_3;

        return $this;
    }

    /**
     * @return Collection|Item[]
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(Item $item): self
    {
        if (!$this->items->contains($item)) {
            $item->addProduct($this);
            $this->items[] = $item;
        }

        return $this;
    }

    public function removeItem(Item $item): self
    {
        if ($this->items->contains($item)) {
            $item->removeProduct($this);
            $this->items->removeElement($item);
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setAddress($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            // set the owning side to null (unless already changed)
            if ($user->getAddress() === $this) {
                $user->setAddress(null);
            }
        }

        return $this;
    }
}

src/Form/AddressType.php
<?php

namespace App\Form;

use App\Entity\Address;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AddressType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('country')
            ->add('department')
            ->add('city')
            ->add('postal_code')
            ->add('address_line_1')
            ->add('address_line_2')
            ->add('address_line_3')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Address::class,
        ]);
    }
}

src/Controller/AddressController.php
<?php

namespace App\Controller;


use App\Entity\Address;
use App\Entity\AddressSearch;
use App\Form\AddressSearchType;
use App\Repository\AddressRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route(path="/address")
 */
class AddressController extends AbstractController
{
    /**
     * @var AddressRepository
     */
    private $addressRepository;

    /**
     * AddressController constructor.
     * @param AddressRepository $addressRepository
     */
    public function __construct(AddressRepository $addressRepository)
    {
        $this->addressRepository = $addressRepository;
    }

    /**
     * @Route("/", name="address.index", methods={"GET"})
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $search = new AddressSearch();
        $form = $this->createForm(AddressSearchType::class, $search);
        $form->handleRequest($request);

        $addresses = $paginator->paginate(
            $this->addressRepository->findAllQuery($search),
            $request->query->getInt('page', 1),
            9
        );

        return $this->render('address/index.html.twig', [
            'addresses' => $addresses,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{id}", name="address.show", methods={"GET"})
     * @param Address $address
     * @return Response
     */
    public function show(Address $address): Response
    {
        return $this->render('address/show.html.twig', [
            'address' => $address,
        ]);
    }
}

templates/address/_form.html.twig
{{ form_start(form, {'attr':{'class': 'mb-4'}}) }}
<div class="bg-light pt-3 px-3 pb-1 mt-4 mb-3">
    <div class="form-row">
        <div class="col-md-5">
            {{ form_row(form.searchInput) }}
        </div>
        <div class="form-group col-md-7">
            {{ form_label(form.searchBy) }}
            <div class="form-inline">
                {{ form_widget(form.searchBy) }}
                <button type="submit" class="btn btn-primary ml-2">Rechercher</button>
            </div>
        </div>
    </div>
</div>
<div class="pt-3 pb-1 mt-2 mb-4">
    <div class="form-row align-items-center">
        <div class="col-auto">
            {{ form_label(form.orderBy) }} :
        </div>
        <div class="col-auto">
            {{ form_widget(form.orderBy, {'attr':{'onchange': 'this.form.submit()'}}) }}
        </div>
        <div class="col-auto">
            {{ form_widget(form.orderDirection) }}
        </div>
    </div>
</div>
{{ form_end(form, {'render_rest' : false}) }}

templates/address/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Voir les adresses' %}

{% block body %}
    <div class="container mt-4">
        <h1>Voir les adresses</h1>
        {{ include('address/_form.html.twig') }}
        <div class="row">
            {% for address in addresses %}
                <div class="col-md-4 col-sm mb-2 mb-md-3">
                    <div class="card">
                        <div class="card-body d-flex">
                            <div>
                                <h3 class="ref">{{ address.name }}</h3>
                                <h3 class="ref">{{ address.country }}</h3>
                                <h3 class="ref">{{ address.department }}</h3>
                                <h3 class="ref">{{ address.postalCode }}, {{ address.city }}</h3>
                                <h3 class="ref">{{ address.addressLine1 }}</h3>
                                <h3 class="ref">{{ address.addressLine2 }}</h3>
                                <h3 class="ref">{{ address.addressLine3 }}</h3>
                            </div>
                            <div class="ml-auto">
                                <a href="{{ path('address.show', {'id' : address.id}) }}">icone</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
                <tr>
                    <td colspan="10">Aucun résultat</td>
                </tr>
            {% endfor %}
        </div>
        <div class="pagination pagination-container text-center w-100 d-flex justify-content-center">
            {{ knp_pagination_render(addresses) }}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        jQuery('#orderDirection .form-check input').on('change', function (e) {
            this.form.submit();
        });
    </script>
{% endblock %}

templates/address/show.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
{% endblock %}

{% block title %}Détails pour l'adresse "{{ address.name }}"{% endblock %}

{% block body %}
    <div class="container my-4">
        <a href="{{ path('address.index') }}">Retour aux adresses</a>
        <h1 class="red">Détails pour l'adresse "{{ address.name }}"</h1>
        <p class="address_name">{{ address.name }}</p>
        <p class="address_name">{{ address.country }}</p>
        <p class="address_name">{{ address.department }}</p>
        <p class="address_name">{{ address.city }}</p>
        <p class="address_name">{{ address.postalCode }}</p>
        <p class="address_name">{{ address.addressLine1 }}</p>
        <p class="address_name">{{ address.addressLine2 }}</p>
        <p class="address_name">{{ address.addressLine3 }}</p>
    </div>
{% endblock %}

{% block javascripts %}
{% endblock %}